route:
  receiver: 'default'
  group_by: ['alertname', 'severity', 'team']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://host.docker.internal:9000/api/v1/admin/webhook/alerts'
        send_resolved: true
        http_config:
          timeout: 10s

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
